import os
from pathlib import Path

import pandas as pd
import pytest

import sys
sys.path.insert(0, ".")

from analysis import compute_stats, progression_series, AttachmentStats, ReactionStats
from html_report import write_html_report


@pytest.fixture
def basic_report_args(tmp_path, sample_messages_df):
    stats = compute_stats(sample_messages_df)
    monthly = progression_series(sample_messages_df)
    return {
        "out_dir": str(tmp_path),
        "contact": "+1234",
        "stats": stats,
        "monthly": monthly,
        "summary_text": "This is the **summary**.",
    }


class TestWriteHtmlReport:
    def test_creates_file(self, basic_report_args):
        path = write_html_report(**basic_report_args)
        assert os.path.exists(path)
        assert path.endswith(".html")

    def test_contains_contact(self, basic_report_args):
        path = write_html_report(**basic_report_args)
        content = Path(path).read_text()
        assert "+1234" in content

    def test_contains_chart_js(self, basic_report_args):
        path = write_html_report(**basic_report_args)
        content = Path(path).read_text()
        assert "chart.js" in content.lower() or "Chart" in content

    def test_summary_rendered_as_html(self, basic_report_args):
        path = write_html_report(**basic_report_args)
        content = Path(path).read_text()
        assert "<strong>summary</strong>" in content

    def test_xss_prevention(self, tmp_path, sample_messages_df):
        stats = compute_stats(sample_messages_df)
        monthly = progression_series(sample_messages_df)
        malicious = '<script>alert("xss")</script>'
        path = write_html_report(
            str(tmp_path), malicious, stats, monthly, "safe summary"
        )
        content = Path(path).read_text()
        assert "<script>alert" not in content
        assert "&lt;script&gt;" in content

    def test_events_rendered(self, tmp_path, sample_messages_df):
        stats = compute_stats(sample_messages_df)
        monthly = progression_series(sample_messages_df)
        events = pd.DataFrame({
            "date": ["2024-01-15"],
            "title": ["Big day"],
            "detail": ["Something happened"],
            "category": ["milestone"],
            "score": [0.9],
            "quote": ["wow"],
        })
        path = write_html_report(
            str(tmp_path), "+1234", stats, monthly, "summary",
            events_df=events,
        )
        content = Path(path).read_text()
        assert "Big day" in content
        assert "Key Events" in content

    def test_events_xss_prevention(self, tmp_path, sample_messages_df):
        stats = compute_stats(sample_messages_df)
        monthly = progression_series(sample_messages_df)
        events = pd.DataFrame({
            "date": ["2024-01-15"],
            "title": ['<img src=x onerror="alert(1)">'],
            "detail": ["safe"],
            "category": ["milestone"],
            "score": [0.9],
            "quote": ['"; DROP TABLE--'],
        })
        path = write_html_report(
            str(tmp_path), "+1234", stats, monthly, "summary",
            events_df=events,
        )
        content = Path(path).read_text()
        assert 'onerror="alert' not in content
        assert "&lt;img" in content

    def test_attachments_section(self, tmp_path, sample_messages_df, sample_attachments_df):
        stats = compute_stats(sample_messages_df, sample_attachments_df)
        monthly = progression_series(sample_messages_df)
        path = write_html_report(
            str(tmp_path), "+1234", stats, monthly, "summary"
        )
        content = Path(path).read_text()
        assert "Attachments" in content
        assert "Photos" in content

    def test_reactions_section(self, tmp_path, sample_messages_df, sample_reactions_df):
        stats = compute_stats(sample_messages_df, reactions_df=sample_reactions_df)
        monthly = progression_series(sample_messages_df)
        path = write_html_report(
            str(tmp_path), "+1234", stats, monthly, "summary"
        )
        content = Path(path).read_text()
        assert "Reactions" in content
        assert "Loves" in content

    def test_footer_has_timestamp(self, basic_report_args):
        path = write_html_report(**basic_report_args)
        content = Path(path).read_text()
        assert "Generated by" in content
